import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import Authlinks from '@/components/auth/authLinks';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen grid grid-rows-[auto,1fr,auto]">
          {/* Header */}
          <header className="bg-primary text-primary-foreground h-16 px-4 flex items-center justify-between">
            <div className="flex items-center">
              <Link href="/" className="text-2xl font-bold">
                Logo
              </Link>
            </div>
            <div className="flex items-center space-x-4">
              <Authlinks />
            </div>
          </header>

          {/* Main Content */}
          {children}

          {/* Footer */}
          <footer className="bg-muted text-muted-foreground p-4 text-center">
            <p>&copy; 2023 Your Company Name. All rights reserved.</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
